### ISSUE TITLE
Firefox Release Needed

### ISSUE THREAD

**Issue by GQH123** [hailengc/BingTranslator#1]
Hi, this extension is really useful and convenient for my daily views in various websites full of english. But while it runs perfectly on Chrome/Chromium, it cannot be installed on Firefox. So would you like to develop a version for Firefox? It will help we a lot and I'm really appreciated for that if you could get it released :)

**Comment by hailengc** [comment]
Hi,

Thank you for using the tool and I'm very glad you like it :)

As I mentioned in README, "Currently this extension is built on Manifest V2, however Google will stop support V2 start from 2023. I'll migrate this extension to Manifest V3 before that, hopefully with some bug fixing as well. See [Manifest V2 support timeline](https://developer.chrome.com/docs/extensions/mv3/mv2-sunset/)."

My next goal will be migrate this tool to "Manifest V3" so it can continue run on Chrome, and after that I'll be able to look if I can have it for Firefox.

Hailong

**Comment by hailengc** [comment]
Hey just let you know, migration to Manifest V3 is done,  please upgrade to your BingTranslatorX to the latest version.

However I still don't have time to look into having a version for Firefox.
